#!/usr/bin/env python

"""
This script shows how a package manager could pass configuration to services. 

Usage: Run "jpm start" inside of a folder with a package.json file

It should be noted how this example requires no additional changes to the Jolie
language. The script will simply read constants from the "constants" property,
convert these to constants and pass them to the Jolie interpreter. Do note that
this script is by no means intended to be complete, but is simply intended to
show off what is currently possible.
"""

import json
import sys
from subprocess import call

if (len(sys.argv) >= 2 and sys.argv[1] == "start"): 
    with open("package.json") as package_file:
        package_data = json.load(package_file)

    arguments = ["jolie"]

    if "constants" in package_data:
        constants = package_data["constants"]
        constants_keys = constants.keys()

        for key in constants_keys:
            obj = constants[key]
            for key2 in obj.keys():
                arguments.append("-C")
                arguments.append("%s_%s=\"%s\"" % (key, key2, obj[key2]))

    arguments.append(package_data["main"])
    call(arguments)
else:
    print "Usage: jpm start"
